### ISSUE TITLE
Player movement is incorrect

### ISSUE THREAD

**Issue by Retoxified** [farteronline/battle-sim#3]
In-game, in open areas the game paths the player horizontally or vertically first, and completes diagonal movement at the end of the path(see below screenshots)
![image](https://github.com/farteronline/battle-sim/assets/3201397/7c708897-de42-437d-8147-2766f73d2dd1)
![image](https://github.com/farteronline/battle-sim/assets/3201397/43527046-9128-4c9c-99f2-09690ea5627c)

In the simulator it paths diagonal first followed by horizontal. This makes little difference for single tick moves, but if he spears it would make a difference if you choose to run further back(in sim you'd dodge, ingame you'd get hit.)

**Comment by farteronline** [comment]
done
