### ISSUE TITLE
Please replace the wav files with my recommendations

### ISSUE THREAD

**Issue by Bablaca** [farteronline/battle-sim#4]
Hey man, this simulator is incredibly done! However I'd like the sound .wav files to be replaced by my attached files (all in a zip). I've carefully analyzed the original sound files so hopefully my new ones should match up perfectly in terms of timing!
[ingame_Sol_sounds.zip](https://github.com/farteronline/battle-sim/files/15018658/ingame_Sol_sounds.zip)

**Comment by Bablaca** [comment]
Nvm, just saw the issue with copyright. Hope I can get this working in my local with customizations though

**Comment by farteronline** [comment]
yes i dont want to commit copyright infringement. To run it locally I use
```
~/Documents/git/sol
python -m http.server
```

and then visit http://localhost:8000
